Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function

In [1]:
#Quetsion1
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
lst1=arr.tolist()
print(lst1)

[[1, 2, 3], [4, 5, 6]]


Question 2 

Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function

In [4]:
#Question2
#with function method
import numpy as np
arr=np.array([(1,5,2),(6,8,5),(8,6,10)])
trace=np.trace(arr)
print(arr)
print("the sum of the diagonal elements is;",trace)


[[ 1  5  2]
 [ 6  8  5]
 [ 8  6 10]]
the sum of the diagonal elements is; 19


In [9]:
#withput function
import numpy as np
arr=np.array([(1,8,5),(5,74,5),(7,9,2)])
i=arr[0,0]
j=arr[1,1]
k=arr[2,2]
print(i+j+k)

77


Question 3

Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 

In [20]:
a=np.array([[1,2],[3,5]])
x=2
print(a[a>x])

[3 5]


Question 4

Given two arrays A&B having the same shape. 

The task is to apply addition by hand: C is the new array. 

In [18]:
#question 4
A=np.array([[1,8,5],[5,6,3]],dtype=np.float64)
B=np.array([[78,4,3],[8,52,9]],dtype=np.float64)
C=A+B
print(C)

[[79. 12.  8.]
 [13. 58. 12.]]


Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [35]:
#question5

import numpy as np
arr=np.array([(1,5,2),(8,5,3),(84,9,6)])
print(arr)
R=0
R1=0
R2=0
for i in arr[0]:
  R=R+i
print(R/3)
for j in arr[1]:
  R1=R1+j
print(R1/3)
for k in arr[2]:
  R2=R2+k
print(R2/3)




[[ 1  5  2]
 [ 8  5  3]
 [84  9  6]]
2.6666666666666665
5.333333333333333
33.0
